# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  # assertions:
  #   - resource: Microsoft.Windows.Developer/OsVersion
  #     directives:
  #       description: Verify min OS version requirement
  #       allowPrerelease: true
  #     settings:
  #       MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget

  configurationVersion: 0.2.0