# https://starship.rs/config/#configuration
add_newline = true

format = """
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$dotnet\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$php\
$python\
$ruby\
$rust\
$line_break\
$character\
"""

[time]
disabled = false
format = "[\\[($time)\\] ]($style)"
time_format = "%Y/%m/%d %T"
style = "yellow"

[directory]
truncation_length = 64
truncation_symbol = "…/"

[git_branch]
disabled = false
symbol = ""
truncation_length = 100
truncation_symbol = ""
style = "bold purple"
always_show_remote = true

[git_commit]
disabled = false
commit_hash_length = 7
style = "bold green"
only_detached = true

[git_status]
disabled = false
ahead = "(⇡${count} )"
diverged = "(⇡${ahead_count}⇣${behind_count} )"
behind = "(⇣${count} )"
format = '[$ahead_behind]($style)([\[$all_status\] ]($style))'
style = "red"
untracked = "U$count"
staged = "A$count"
modified = "M$count"
deleted = "D$count"

[character]
disabled = false
format = "$symbol"
success_symbol = "[\\(๑˃̵ᴗ˂̵\\)و❯ ](cyan)"
error_symbol = "[\\(๑°д°\\)۶❯ ](red)"

